apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - base/api-gateway/api-gateway-deployment.yaml
  - base/configs/app-config.yaml
  - base/api-gateway/api-gateway-service.yaml
  - auth-service/auth-service.yaml
  - auth-service/auth-service-deployment.yaml
  - base/postgres-service/postgres-deployment.yaml
  - base/postgres-service/postgres-service.yaml
  - base/rabbitmq-service/rabbitmq-deployment.yaml
  - base/rabbitmq-service/rabbitmq-service.yaml

images:
  - name: api-gateway  # باید با container name در deployment هماهنگ باشد
    newName: 
    newTag: api-gateway-ae904dcf1e3caf7d4b910a6699be53a5f234fde0

  - name: auth-service  # باید با container name در deployment هماهنگ باشد
    newName: 
    newTag: auth-service-ae904dcf1e3caf7d4b910a6699be53a5f234fde0
