apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  # مطمئن شو این مسیرها درست هستند
  - api-gateway/api-gateway-deployment.yaml
  - api-gateway/api-gateway-service.yaml
  - auth-service/auth-service-deployment.yaml
  - auth-service/auth-service.yaml
  - postgres-service/postgres-deployment.yaml
  - postgres-service/postgres-service.yaml
  - rabbitmq-service/rabbitmq-deployment.yaml
  - rabbitmq-service/rabbitmq-service.yaml
  - configs/app-config.yaml
#  - configs/secrets.yaml

images:
  - name: api-gateway
    newName: abbass69/api-gateway
    newTag: latest
  - name: auth-service
    newName: abbass69/auth-service
    newTag: latest
  - name: postgres
    newName: postgres
    newTag: 15-alpine
  - name: rabbitmq
    newName: rabbitmq
    newTag: 3-management-alpine

# اضافه کردن secret generator
secretGenerator:
  - name: app-secrets
    literals:
      - DB_HOST=postgres-service.production.svc.cluster.local
      - DB_PORT=5432
      - DB_USERNAME=prod_user
      - DB_PASSWORD=prod_user
      - DB_NAME=microservice_prod
      - JWT_SECRET=jafar.com
      - RABBITMQ_URI=amqp://prod_user:CHANGE_ME@rabbitmq.production.svc.cluster.local:5672/
    type: Opaque

# اینجا اصلاح شده - از labels استفاده کن
labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/environment: production
      app.kubernetes.io/part-of: microservice