apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/abbassmortazavi/go-microservice'
    targetRevision: HEAD
    path: 'infra/development/k8s'
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true

