apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: Development

  # ConfigMaps - Secrets

  # Databases

  # Message Queue

  # Services

resources:
- configs/app-config.yaml
- configs/secrets.yaml
- postgres-service/postgres-deployment.yaml
- postgres-service/postgres-service.yaml
- rabbitmq-service/rabbitmq-deployment.yaml
- rabbitmq-service/rabbitmq-service.yaml
- api-gateway/api-gateway-deployment.yaml
- api-gateway/api-gateway-service.yaml
- auth-service/auth-service-deployment.yaml
- auth-service/auth-service.yaml



# Image transformers



images:
- name: api-gateway
  newTag: a64100d3c026851fed6e42c0ffed60f43d95e6fb
- name: auth-service
  newTag: a64100d3c026851fed6e42c0ffed60f43d95e6fb
- name: postgres
  newName: postgres
  newTag: 15-alpine
- name: rabbitmq
  newName: rabbitmq
  newTag: 3-management-alpine

# Common labels
commonLabels:
  app.kubernetes.io/environment: development
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: microservice
