apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: Development

  # ConfigMaps - Secrets

  # Databases

  # Message Queue

  # Services

resources:
- configs/app-config.yaml
- configs/secrets.yaml
- postgres-service/postgres-deployment.yaml
- postgres-service/postgres-service.yaml
- rabbitmq-service/rabbitmq-deployment.yaml
- rabbitmq-service/rabbitmq-service.yaml
- api-gateway/api-gateway-deployment.yaml
- api-gateway/api-gateway-service.yaml
- auth-service/auth-service-deployment.yaml
- auth-service/auth-service.yaml



# Image transformers



images:
- name: api-gateway
  newTag: 5bdf0e473438119fabeb7b2f61232583fe09ad1d
- name: auth-service
  newTag: 5bdf0e473438119fabeb7b2f61232583fe09ad1d
- name: postgres
  newName: postgres
  newTag: 15-alpine
- name: rabbitmq
  newName: rabbitmq
  newTag: 3-management-alpine

# Common labels
commonLabels:
  app.kubernetes.io/environment: development
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: microservice
