# infra/k8s/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-gateway-deployment.yaml
  - app-config.yaml
  - api-gateway-service.yaml

# This namespace will be applied to ALL resources in the list
namespace: production