apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-gateway-deployment.yaml
  - app-config.yaml
  - api-gateway-service.yaml

namespace: production

images:
  - name: abbass69/microservice
    newName: abbass69/microservice
    newTag: api-gateway-PLACEHOLDER
