apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-gateway/api-gateway-deployment.yaml
  - app-config.yaml
  - api-gateway/api-gateway-service.yaml
  - auth-service/auth-service-service.yaml
  - auth-service/auth-service-deployment.yaml

namespace: production

images:
  - name: abbass69/microservice
    newName: abbass69/microservice
    newTag: api-gateway-c3fcaac6023fc3b0da1d9e96913bfe0e3bd8b603
