name: Deploy to Development

concurrency:
  group: development-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: ["develop", "feature/**", "bugfix/**"]

jobs:
  # استفاده از تست ساده
  tests:
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
    with:
      environment: 'development'

  build:
    uses: ./.github/workflows/run-build.yml
    needs: tests
    secrets: inherit
    with:
      environment: 'development'

  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: build
    secrets: inherit
    with:
      environment: 'development'