name: Deploy to Development

concurrency:
  group: development-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: ["develop", "feature/**", "bugfix/**"]

# ðŸ”¥ ØªÙ†Ø¸ÛŒÙ… permissions Ø¯Ø± Ø§ÛŒÙ† Ø³Ø·Ø­
permissions:
  contents: write  # Ø¨Ø±Ø§ÛŒ push ØªØºÛŒÛŒØ±Ø§Øª
  packages: write  # Ø¨Ø±Ø§ÛŒ push Ø¨Ù‡ Docker Hub
  id-token: write  # Ø¨Ø±Ø§ÛŒ authentication

jobs:
  # Ù…Ø±Ø­Ù„Ù‡ Û±: ØªØ³Øª
  tests:
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit

  # Ù…Ø±Ø­Ù„Ù‡ Û²: Ø³Ø§Ø®Øª images
  build:
    uses: ./.github/workflows/run-build.yml
    needs: tests
    secrets: inherit

  # Ù…Ø±Ø­Ù„Ù‡ Û³: Ø¯ÛŒÙ¾Ù„ÙˆÛŒ
  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: build
    secrets: inherit
    with:
      environment: 'development'